---

language: python
python: "2.7"
sudo: required
dist: trusty

# https://nzbget.net/prerequisites-for-c++-compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python-pip
      - g++-4.9

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - nzbget --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
