---

- name: Install build tools
  ansible.builtin.apt:
    name:
      - ca-certificates
      - make
      - gcc
      - g++
      - pkg-config
      - libxml2-dev
      - libncurses-dev
      - libssl-dev
      - zlib1g-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Get source code
  ansible.builtin.unarchive:
    src: https://github.com/nzbgetcom/nzbget/archive/refs/tags/v{{ nzbget_version }}.tar.gz
    dest: /tmp
    remote_src: True

- name: Make clean
  ansible.builtin.command: make clean
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  failed_when: no
  changed_when: yes

- name: Configure
  ansible.builtin.command: >
    ./configure
    --sysconfdir=/etc
    --localstatedir=/var
    --datarootdir=/usr/share
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: yes

- name: Make
  ansible.builtin.command: make -j{{ ansible_processor_vcpus }}
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: yes

- name: Install
  ansible.builtin.command: make install
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  become: yes
  changed_when: yes
  notify: Restart_nzbget
