---

- name: install prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ca-certificates
    - make
    - gcc
    - g++
    - pkg-config
    - libxml2-dev
    - libncurses5-dev
    - libssl-dev
    - zlib1g-dev
  become: yes

- name: get source code
  unarchive:
    src: https://github.com/nzbget/nzbget/releases/download/v{{ nzbget_version }}/nzbget-{{ nzbget_version }}-src.tar.gz
    dest: /tmp
    remote_src: True

- name: make clean
  command: make clean
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  ignore_errors: yes

- name: configure
  command: >
    ./configure
    --sysconfdir=/etc
    --localstatedir=/var
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}

- name: make
  command: make
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}

- name: install
  command: make install
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }} 
  become: yes
#  notify: restart_nzbget
