---

- name: Install build tools
  ansible.builtin.apt:
    name:
      - autoconf
      - ca-certificates
      - make
      - gcc
      - g++
      - pkg-config
      - libxml2-dev
      - '{{ nzbget_libboost_package }}'
      - libncurses-dev
      - libssl-dev
      - zlib1g-dev
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Get source code
  ansible.builtin.unarchive:
    src: https://github.com/nzbgetcom/nzbget/archive/refs/tags/v{{ nzbget_version }}.tar.gz
    dest: /tmp
    remote_src: true

- name: Create configure
  ansible.builtin.command: autoreconf --install
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: true

- name: Configure
  ansible.builtin.command: >
    ./configure
    --sysconfdir=/etc
    --localstatedir=/var
    --datarootdir=/usr/share
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: true

- name: Build
  ansible.builtin.command: make -j{{ ansible_processor_vcpus }}
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: true

- name: Install
  ansible.builtin.command: make install
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  become: true
  changed_when: true
  notify: Restart_nzbget

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/nzbget-{{ nzbget_version }}
    state: absent
  become: true
