---

- name: install build tools
  apt:
    name:
      - ca-certificates
      - make
      - gcc
      - g++
      - pkg-config
      - libxml2-dev
      - libncurses-dev
      - libssl-dev
      - zlib1g-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: get source code
  unarchive:
    src: https://github.com/nzbget/nzbget/releases/download/v{{ nzbget_version }}/nzbget-{{ nzbget_version }}-src.tar.gz
    dest: /tmp
    remote_src: True

- name: make clean
  command: make clean
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  failed_when: no
  changed_when: yes

- name: configure
  command: >
    ./configure
    --sysconfdir=/etc
    --localstatedir=/var
    --datarootdir=/usr/share
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: yes

- name: make
  command: make -j{{ ansible_processor_vcpus }}
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  changed_when: yes

- name: install
  command: make install
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  become: yes
  changed_when: yes
  notify: restart_nzbget
