---

- name: Install build tools
  ansible.builtin.apt:
    name:
      - ca-certificates
      - cmake
      - make
      - gcc
      - g++
      - pkg-config
      - libxml2-dev
      - libboost-json1.81-dev
      - libncurses-dev
      - libssl-dev
      - zlib1g-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Get source code
  ansible.builtin.unarchive:
    src: https://github.com/nzbgetcom/nzbget/archive/refs/tags/v{{ nzbget_version }}.tar.gz
    dest: /tmp
    remote_src: True

- name: Create build folder
  ansible.builtin.file:
    path: /tmp/nzbget-{{ nzbget_version }}/build/
    state: directory
    mode: '0755'
  become: yes

- name: Configure
  ansible.builtin.command: cmake ..
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}/build/
  changed_when: yes

- name: Build
  ansible.builtin.command: cmake --build . -j {{ ansible_processor_vcpus }}
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}/build/
  changed_when: yes

- name: Install
  ansible.builtin.command: cmake --install .
  args:
    chdir: /tmp/nzbget-{{ nzbget_version }}
  become: yes
  changed_when: yes
  notify: Restart_nzbget

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/nzbget-{{ nzbget_version }}
    state: absent
  become: true
