---

- name: create run folder
  file:
    path: /run/nzbget
    state: directory
    mode: 0755
    owner: "{{ nzbget_user }}"
  become: yes

- name: check for systemd
  command: systemctl --version
  register: nzbget_systemctl_version
  ignore_errors: yes

- name: add nzbget.service
  template:
    src: nzbget.service.ini
    dest: /lib/systemd/system/nzbget.service
    mode: 0644
  become: yes
  when: nzbget_systemctl_version.rc == 0
  notify:
    - nzbget_reload_systemd
    - restart_nzbget

- name: add nzbget.init
  template:
    src: nzbget.init.sh
    dest: /etc/init.d/nzbget
    mode: "a+x"
  become: yes
  when: nzbget_systemctl_version.rc != 0
  notify: restart_nzbget

- name: touch nzbget.conf
  file:
    path: /etc/nzbget.conf
    state: touch
    mode: 0644
  become: yes
