---

- name: create run folder
  file:
    path: /run/nzbget
    state: directory
    mode: 0755
    owner: "{{ nzbget_user }}"
  become: yes

- name: perma run folder
  template:
    src: tmpfiles.conf
    dest: /etc/tmpfiles.d/nzbget.conf
    mode: 0644
  become: yes

- name: add nzbget.service
  template:
    src: nzbget.service.ini
    dest: /lib/systemd/system/nzbget.service
    mode: 0644
  become: yes
  notify:
    - nzbget_reload_systemd
    - restart_nzbget

- name: touch nzbget.conf
  file:
    path: /etc/nzbget.conf
    state: touch
    mode: 0644
  become: yes
