---

- name: get nzbget version
  command: nzbget --version
  register: nzbget_version_current
  ignore_errors: yes
  changed_when: no

- import_tasks: compile.yml
  when: nzbget_version_current is failure or not nzbget_version_current.stdout is search(nzbget_version_string_match)

- import_tasks: install.yml

- import_tasks: tools.yml
