---

- name: nzbget_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yhes

- name: restart_nzbget
  ansible.builtin.systemd:
    name: nzbget
    state: restarted
    enabled: yes
  become: yes
