---

- name: Nzbget_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart_nzbget
  ansible.builtin.systemd:
    name: nzbget
    state: restarted
    enabled: true
  become: true
